# Alias
alias wf='~/bin/WorkFlowy/workflowy &'
alias py='python3'
alias sl='sl | lolcat'
alias fortune='fortune | lolcat'
alias cmatrix='cmatrix | lolcat'
alias rm='trash-put'
alias ya='yazi'
alias bashrc='vi ~/.bashrc'
alias vv='nvim'
alias vi='vim'
alias hs='history'
alias lg='lazygit'
alias gg='git'
alias grep='grep --color=auto -n -P'
alias dot='cd ~/dotfiles.d/bash/'
alias bcat='batcat'
alias cl='clear'
alias gs='echo "gs(ghost script) is disabled by alias setting"'
alias dirs='dirs -v'
alias gd=pushd
alias pd=popd
alias slurp='pushd - && pushd' # ref oreilly efficiend linux command
